backend:
  name: git-gateway
  branch: main

site_url: https://qazzplitt.netlify.app
display_url: https://qazzplitt.netlify.app

logo_url: /logo.png

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: products
    label: Каталог

    files:
      - file: content/products.json
        label: Товары
        name: products

        fields:
          - label: Товары
            name: items
            widget: list
